//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Drupal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions
    {
        public long uid { get; set; }
        public string sid { get; set; }
        public string ssid { get; set; }
        public string hostname { get; set; }
        public int timestamp { get; set; }
        public int cache { get; set; }
        public byte[] session { get; set; }
    }
}
