//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Drupal
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public long uid { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
        public string mail { get; set; }
        public string theme { get; set; }
        public string signature { get; set; }
        public string signature_format { get; set; }
        public int created { get; set; }
        public int access { get; set; }
        public int login { get; set; }
        public sbyte status { get; set; }
        public string timezone { get; set; }
        public string language { get; set; }
        public int picture { get; set; }
        public string init { get; set; }
        public byte[] data { get; set; }
    }
}
