//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acciones()
        {
            this.Rol_Acciones = new HashSet<Rol_Acciones>();
        }
    
        public int AccionId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string ReferenciaHTML { get; set; }
        public string ReferenciaJS { get; set; }
        public string ReferenciasWebAPI { get; set; }
        public string ReferenciasAux { get; set; }
        public Nullable<int> TipoAccionId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Icono { get; set; }
        public string URL { get; set; }
        public bool Borrado { get; set; }
        public Nullable<int> Secuencia { get; set; }
    
        public virtual TipoAccion TipoAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol_Acciones> Rol_Acciones { get; set; }
    }
}
