//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agenda_Usuario()
        {
            this.Entrevistas = new HashSet<Entrevistas>();
        }
    
        public int IdAgenda_Usuario { get; set; }
        public System.DateTime FechaAgenda { get; set; }
        public string Hora { get; set; }
        public bool IsHoraBloqueada { get; set; }
        public bool IsHoraCancelada { get; set; }
        public Nullable<int> IdPostulante { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string JoinUrl { get; set; }
        public string StarUrl { get; set; }
        public string Uuid { get; set; }
        public string Id { get; set; }
        public string UserIdZoom { get; set; }
        public int IdPais { get; set; }
    
        public virtual Paises_Bac Paises_Bac { get; set; }
        public virtual Postulante Postulante { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevistas> Entrevistas { get; set; }
    }
}
