//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueue
    {
        public int IdEmailQueue { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string Body { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateSended { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Subject { get; set; }
    }
}
