//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrevistas()
        {
            this.Entrevistas_Videos = new HashSet<Entrevistas_Videos>();
            this.Preguntas_Entrevistas = new HashSet<Preguntas_Entrevistas>();
        }
    
        public int IdEntrevista { get; set; }
        public int IdPostulante { get; set; }
        public Nullable<int> IdFeriaEmpleo { get; set; }
        public Nullable<int> IdAgenda { get; set; }
        public int TipoEntrevista { get; set; }
        public System.DateTime FechaEntrevista { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<int> IdEstadoEntrevista { get; set; }
        public Nullable<int> IdTipoEntrevista { get; set; }
        public Nullable<int> IdUsuarioCreador { get; set; }
        public Nullable<int> CalificacionGeneral { get; set; }
    
        public virtual Agenda_Usuario Agenda_Usuario { get; set; }
        public virtual EstadoEntrevista EstadoEntrevista { get; set; }
        public virtual FeriaEmpleo FeriaEmpleo { get; set; }
        public virtual Postulante Postulante { get; set; }
        public virtual Puestos Puestos { get; set; }
        public virtual TipoEntrevista TipoEntrevista1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevistas_Videos> Entrevistas_Videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas_Entrevistas> Preguntas_Entrevistas { get; set; }
    }
}
