//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevistas_Videos
    {
        public int IdEntrevista_Video { get; set; }
        public string UrlVideo { get; set; }
        public int IdEntrevista { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public string IdZiggeo { get; set; }
    
        public virtual Entrevistas Entrevistas { get; set; }
        public virtual Preguntas Preguntas { get; set; }
    }
}
