//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeriaEmpleo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeriaEmpleo()
        {
            this.Entrevistas = new HashSet<Entrevistas>();
            this.FeriaEmpleo_Entrevistadores = new HashSet<FeriaEmpleo_Entrevistadores>();
            this.FeriaEmpleo_Puestos = new HashSet<FeriaEmpleo_Puestos>();
            this.Paises_Bac_FeriaEmpleo = new HashSet<Paises_Bac_FeriaEmpleo>();
        }
    
        public int IdFeriaEmpleo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int FrecuenciaHora { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFinal { get; set; }
        public bool FeriaCerrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevistas> Entrevistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeriaEmpleo_Entrevistadores> FeriaEmpleo_Entrevistadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeriaEmpleo_Puestos> FeriaEmpleo_Puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paises_Bac_FeriaEmpleo> Paises_Bac_FeriaEmpleo { get; set; }
    }
}
