//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises_Bac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paises_Bac()
        {
            this.Agenda_Usuario = new HashSet<Agenda_Usuario>();
            this.Paises_Bac_FeriaEmpleo = new HashSet<Paises_Bac_FeriaEmpleo>();
            this.Paises_Bac_Usuario = new HashSet<Paises_Bac_Usuario>();
            this.PaisPostulante = new HashSet<PaisPostulante>();
            this.Puestos_Paises_BAC = new HashSet<Puestos_Paises_BAC>();
            this.Zona1 = new HashSet<Zona1>();
        }
    
        public int IdPais { get; set; }
        public string Descripcion { get; set; }
        public bool Borrado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ZonaHoraria { get; set; }
        public string Sigla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda_Usuario> Agenda_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paises_Bac_FeriaEmpleo> Paises_Bac_FeriaEmpleo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paises_Bac_Usuario> Paises_Bac_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaisPostulante> PaisPostulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puestos_Paises_BAC> Puestos_Paises_BAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zona1> Zona1 { get; set; }
    }
}
