//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulante()
        {
            this.Agenda_Usuario = new HashSet<Agenda_Usuario>();
            this.AreasPostulante = new HashSet<AreasPostulante>();
            this.Comentarios = new HashSet<Comentarios>();
            this.Entrevistas = new HashSet<Entrevistas>();
            this.ExperienciaLaboral = new HashSet<ExperienciaLaboral>();
            this.Habilidades_Postulante = new HashSet<Habilidades_Postulante>();
            this.Idiomas_Postulante = new HashSet<Idiomas_Postulante>();
            this.PaisPostulante = new HashSet<PaisPostulante>();
            this.Postulante_Discapacidad = new HashSet<Postulante_Discapacidad>();
            this.Postulante_MediosInformacion = new HashSet<Postulante_MediosInformacion>();
            this.Puestos_Postulante = new HashSet<Puestos_Postulante>();
            this.ReferenciasLaborales = new HashSet<ReferenciasLaborales>();
            this.Titulos = new HashSet<Titulos>();
        }
    
        public int IdPostulante { get; set; }
        public string NombreCompleto { get; set; }
        public string Nacionalidad { get; set; }
        public string Identificacion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<bool> Genero { get; set; }
        public int IdEstadoCivil { get; set; }
        public string Telefono { get; set; }
        public string ImagenURL { get; set; }
        public string OtraDiscapacidad { get; set; }
        public int PaisRecidencia { get; set; }
        public Nullable<bool> Vehiculo { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdZona1 { get; set; }
        public Nullable<int> IdZona2 { get; set; }
        public Nullable<int> IdZona3 { get; set; }
        public bool EstudiaActualidad { get; set; }
        public int GradoAcademico { get; set; }
        public string Profesion { get; set; }
        public int IdPretensionSalarial { get; set; }
        public string DescripcionCualidades { get; set; }
        public string DescripcionVentajaCompetitiva { get; set; }
        public bool TrabajoBAC { get; set; }
        public string CurriculumURL { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuario { get; set; }
        public bool Borrado { get; set; }
        public bool Favorito { get; set; }
        public Nullable<int> IdTipoLicencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda_Usuario> Agenda_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreasPostulante> AreasPostulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevistas> Entrevistas { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaLaboral> ExperienciaLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habilidades_Postulante> Habilidades_Postulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Idiomas_Postulante> Idiomas_Postulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaisPostulante> PaisPostulante { get; set; }
        public virtual Zona2 Zona2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulante_Discapacidad> Postulante_Discapacidad { get; set; }
        public virtual Zona3 Zona3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulante_MediosInformacion> Postulante_MediosInformacion { get; set; }
        public virtual PretensionSalarial PretensionSalarial { get; set; }
        public virtual Zona1 Zona1 { get; set; }
        public virtual TipoLicencia TipoLicencia { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puestos_Postulante> Puestos_Postulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciasLaborales> ReferenciasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Titulos> Titulos { get; set; }
    }
}
