//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestos_Postulante
    {
        public int IdPuesto { get; set; }
        public int IdPostulante { get; set; }
        public bool Borrado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdEstadoPerfil { get; set; }
    
        public virtual EstadoPerfil EstadoPerfil { get; set; }
        public virtual Postulante Postulante { get; set; }
        public virtual Puestos Puestos { get; set; }
    }
}
