//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puestos()
        {
            this.Entrevistas = new HashSet<Entrevistas>();
            this.FeriaEmpleo_Puestos = new HashSet<FeriaEmpleo_Puestos>();
            this.Puesto_TipoJornada = new HashSet<Puesto_TipoJornada>();
            this.Puestos_Idiomas = new HashSet<Puestos_Idiomas>();
            this.Puestos_Paises_BAC = new HashSet<Puestos_Paises_BAC>();
            this.Puestos_Postulante = new HashSet<Puestos_Postulante>();
            this.PuestosPublicacionTrack = new HashSet<PuestosPublicacionTrack>();
            this.RequisitosPuesto = new HashSet<RequisitosPuesto>();
        }
    
        public int IdPuesto { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string ImagenURL { get; set; }
        public int IdArea { get; set; }
        public int IdNivelAcademico { get; set; }
        public System.DateTime FechaCierreOferta { get; set; }
        public bool Publicado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<int> IdZona1 { get; set; }
        public Nullable<int> IdDrupal { get; set; }
        public Nullable<System.DateTime> FechaModificacionPublicacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }

        public virtual AreasLaborales AreasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevistas> Entrevistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeriaEmpleo_Puestos> FeriaEmpleo_Puestos { get; set; }
        public virtual NivelAcademico NivelAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puesto_TipoJornada> Puesto_TipoJornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puestos_Idiomas> Puestos_Idiomas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puestos_Paises_BAC> Puestos_Paises_BAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puestos_Postulante> Puestos_Postulante { get; set; }
        public virtual Zona1 Zona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuestosPublicacionTrack> PuestosPublicacionTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitosPuesto> RequisitosPuesto { get; set; }
    }
}
