//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Acciones
    {
        public int IdRol { get; set; }
        public int AccionId { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
    
        public virtual Acciones Acciones { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
