//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int IdSesion { get; set; }
        public int IdUsuario { get; set; }
        public string User_key { get; set; }
        public string Secret_key { get; set; }
        public string Hostname { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaExpiración { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
