//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulos
    {
        public int IdTitulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> TipoCertificacion { get; set; }
        public Nullable<int> IdPostulante { get; set; }
        public string Institucion { get; set; }
        public Nullable<int> AnioInicio { get; set; }
        public Nullable<int> AnioFin { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual NivelAcademico NivelAcademico { get; set; }
        public virtual Postulante Postulante { get; set; }
    }
}
