//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Agenda_Usuario = new HashSet<Agenda_Usuario>();
            this.Bitacora_Log = new HashSet<Bitacora_Log>();
            this.Comentarios = new HashSet<Comentarios>();
            this.FeriaEmpleo_Entrevistadores = new HashSet<FeriaEmpleo_Entrevistadores>();
            this.Paises_Bac_Usuario = new HashSet<Paises_Bac_Usuario>();
            this.Postulante = new HashSet<Postulante>();
            this.Sesiones = new HashSet<Sesiones>();
            this.Usuario_Roles = new HashSet<Usuario_Roles>();
        }
    
        public int IdUsuario { get; set; }
        public Nullable<int> IdDrupal { get; set; }
        public string NombreCompleto { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Borrado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdPais { get; set; }
        public int IdTipoLogin { get; set; }
        public string UrlIngresoTemporal { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public bool CambioContrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda_Usuario> Agenda_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora_Log> Bitacora_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeriaEmpleo_Entrevistadores> FeriaEmpleo_Entrevistadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paises_Bac_Usuario> Paises_Bac_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulante> Postulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesiones> Sesiones { get; set; }
        public virtual TipoLogin TipoLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Roles> Usuario_Roles { get; set; }
    }
}
