//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListaPostulanteReporte
    {
        public int IdPostulante { get; set; }
        public string email { get; set; }
        public string NombreCompleto { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Aplicaciones { get; set; }
        public bool Genero { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int PaisRecidencia { get; set; }
        public string IdPaisAplicacion { get; set; }
        public string IdEstadoPerfil { get; set; }
        public string IdIdioma { get; set; }
        public string Porcentaje { get; set; }
        public string ColumnMobile1 { get; set; }
        public string ColumnMobile2 { get; set; }
        public string IdDiscapacidad { get; set; }
    }
}
