//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PostulanteXPuesto
    {
        public int IdPostulante { get; set; }
        public string NombreCompleto { get; set; }
        public string Nacionalidad { get; set; }
        public string Identificacion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool Genero { get; set; }
        public int IdEstadoCivil { get; set; }
        public string Telefono { get; set; }
        public string ImagenURL { get; set; }
        public string OtraDiscapacidad { get; set; }
        public int PaisRecidencia { get; set; }
        public bool Vehiculo { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdZona1 { get; set; }
        public Nullable<int> IdZona2 { get; set; }
        public Nullable<int> IdZona3 { get; set; }
        public bool EstudiaActualidad { get; set; }
        public int GradoAcademico { get; set; }
        public string Profesion { get; set; }
        public int IdPretensionSalarial { get; set; }
        public bool TrabajoBAC { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string IdPais { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Edad { get; set; }
        public int IdPuesto { get; set; }
        public string IdArea { get; set; }
        public int IdDiscapacidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public bool Favorito { get; set; }
        public string ColumnMobile1 { get; set; }
        public string ColumnMobile2 { get; set; }
        public int IdEstadoPerfil { get; set; }
        public string IdPuestosPublicacionTrack { get; set; }
    }
}
