//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_usuarios
    {
        public int IdUsuario { get; set; }
        public Nullable<int> IdDrupal { get; set; }
        public string NombreCompleto { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Borrado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string IdPais { get; set; }
        public string NombrePais { get; set; }
        public string IdRol { get; set; }
        public string NombreRol { get; set; }
        public string ColumnMobile { get; set; }
    }
}
