//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaEmpleoBAC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zona1
    {
        public int IdZona1 { get; set; }
        public string nombreZona { get; set; }
        public int IdPais { get; set; }
        public string nombrePais { get; set; }
        public bool Borrado { get; set; }
    }
}
